"""initial clean migration

Revision ID: 2a73f19219b9
Revises: 69412147940a
Create Date: 2026-01-21 13:59:29.738722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a73f19219b9'
down_revision = '69412147940a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'maintenances', ['maintenance_id'], ['id'])

    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condominium_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('scheduled_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('completed_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'condominios', ['condominium_id'], ['id'])
        batch_op.drop_column('cost')
        batch_op.drop_column('type')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('completed_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('condominium_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('maintenance_id')

    # ### end Alembic commands ###
