"""empty message

Revision ID: 37a78a8d7647
Revises: 402424267416
Create Date: 2026-01-02 15:25:06.557334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a78a8d7647'
down_revision = '402424267416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condominio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'condominios', ['condominio_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('condominio_id')

    # ### end Alembic commands ###
