"""empty message

Revision ID: 69412147940a
Revises: fa531bf33e0a
Create Date: 2026-01-13 13:19:09.435430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69412147940a'
down_revision = 'fa531bf33e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'condominios', ['condominium_id'], ['id'])
        batch_op.create_foreign_key(None, 'expense_statuses', ['expense_status_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expense_status_id')

    op.drop_table('expense_statuses')
    # ### end Alembic commands ###
