"""empty message

Revision ID: 76db0e3fefe1
Revises: 8e22e76c7c61
Create Date: 2026-01-28 16:35:11.013993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76db0e3fefe1'
down_revision = '8e22e76c7c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    # ### end Alembic commands ###
