"""empty message

Revision ID: 8e22e76c7c61
Revises: 5b492ca38050
Create Date: 2026-01-28 14:52:53.688174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e22e76c7c61'
down_revision = '5b492ca38050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominium_id', sa.Integer(), nullable=False),
    sa.Column('visitor_name', sa.String(length=100), nullable=False),
    sa.Column('visitor_rut', sa.String(length=20), nullable=True),
    sa.Column('unit_number', sa.String(length=20), nullable=False),
    sa.Column('patent', sa.String(length=20), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['condominium_id'], ['condominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    # ### end Alembic commands ###
